server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
      timeout: 3600

spring:
  application:
    name: testThymeLeaf

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_thyme?use_ssl=false
    username: root
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379