name: Make Image

on:
    push:
        branches:
            - main

env:
    IMAGE_TAG: latest

defaults:
    run:
        working-directory: ./pnuBookStore
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Login to NCP Registry
              id: login_registry
              run: |
                docker login docker-pnu-bookstore-spring.kr.ncr.ntruss.com --username ${{ secrets.ACCESS_TOKEN }} --password-stdin ${{ secrets.SECRET_TOKEN }}
        
            - name: Docker Build
              run: |
                docker build -t ${{ secrets.REGISTRY }}/${{secrets.REPOSITORY}}:$IMAGE_TAG .
                docker push ${{ secrets.REGISTRY }}/${{secrets.REPOSITORY}}:$IMAGE_TAG
                